import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ContextProvider } from "./context/ContextProvider";
import Header from "./common/Header";
import Username from "./common/Username";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "This is title",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={`${inter.className } dark:bg-gray-800`}>
        <ContextProvider>
          <>
          <Header>
            <Username/>
          </Header>
            {children}
            <Toaster position="top-right" reverseOrder={true} />
          </>
        </ContextProvider>
      </body>
    </html>
  );
}
